### ISSUE TITLE
How to deploy a Logic App Standard that use an XSLT map/schema?

### ISSUE THREAD

**Issue by nour95** [Azure/logicapps#384]
Say that I have a logic app standard that have a workflow that contains an action like "Transform Json To Json" that use an XSLT map. 

I have the following structure for my files:

```tree
|   .gitignore
|   azure-pipelines.yml
|   
+---Integrations
|   +---Artifacts
|   |   +---Maps
|   |   |       myMap.xslt
|   |   |       
|   |   \---Schemas
|   +---LogicApp
|   |       LogicApp-template.json
|   |       
|   +---RequiredIntegerations
|   |       storage-template.json
|   |       
|   \---Workflows
|       |   azure.parameters.json
|       |   connections.json
|       |   host.json
|       |   parameters.json
|       |      
|       \---testXsltWorkflow
|               workflow.json
|               
\---releasePipeline
   |   commit.yml
   |   release.yml
   |   requiredDeployment.yml
   |   
   +---commitJobs
   |       integrations.yml
   |       
   \---releaseJobs
           deployIntegrations.yml
```

I have tried to deploy the map folder in the same way I deploy the workflows inside the yaml file (zip deploy)
I build the map Artifact like this:

```yml
# Build Maps Artifacts
- job: Build_Maps
    displayName: Build_Maps
    dependsOn: Build_LA_Artifact

    pool:
      vmImage: 'ubuntu-18.04'

    # Copy the files to project_output folders
    steps:
    - task: CopyFiles@2
      displayName: 'Create project folder'
      inputs:
        SourceFolder: 'Integrations/'
        Contents: |
          Artifacts/**
        TargetFolder: 'project_output'

    ## convert the files in project_output/Artifacts folder to a zip files 
    ## (i.e. compress the worklflow files into a zip file) and save it in artifiact folder
    - task: ArchiveFiles@2   
      displayName: 'Create project zip'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output/Artifacts'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    ## Publish/deploy the maps inside the LA.
    - task: PublishPipelineArtifact@1
      displayName: 'Publish project zip artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: 'mapsArtifact' 
        publishLocation: 'pipeline'
```
And I deploy the artifacts like this:

```yml
# deploy maps
- deployment: DeployMapsArtifact
    dependsOn: DeployLogicAppArtifact
    
    pool:
      vmImage: 'ubuntu-18.04'
    environment: "${{parameters.environment}}"
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: 'mapsArtifact'             
            - task: AzureFunctionApp@1
              displayName: 'Deploy logic app maps'
              inputs:
                azureSubscription: "${{ parameters.connectedServiceName }}"
                appType: 'functionApp'
                appName:  "${{parameters.LA_name}}-${{ parameters.environment }}" 
                package: '$(Pipeline.Workspace)/mapsArtifact/*.zip'
                deploymentMethod: 'zipDeploy'
```

The deployment succeed but I still can't see my XSLT map inside the Maps tab in my standard logic App.
