### ISSUE TITLE
result() function does not work properly for foreach action in Logic Apps Standard

### ISSUE THREAD

**Issue by probertdaniel** [Azure/logicapps#732]
### Describe the Bug

According to the documentation, the result() function should return an array of actions within a scoped action (e.g. Scope, For-Each, Until) as documented here: [https://learn.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#result](https://learn.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#result).

Each action should show the StartTime, EndTime, Status, Inputs and Outputs.
This is indeed the case for Consumption Logic Apps.
But for Logic Apps Standard, the result() function only works properly for Scope actions, not For-Each actions: it does not display the inputs and outputs for the actions in the array. It does, however, contain StartTime, EndTime, Status etc.

We can test this using the example from the documentation, and testing the same code in both Consumption and Standard:
The sample code is:
```yaml
{
   "actions": {
      "Compose": {
         "inputs": "@result('For_each')",
         "runAfter": {
            "For_each": [
               "Succeeded"
            ]
         },
         "type": "compose"
      },
      "For_each": {
         "actions": {
            "HTTP": {
               "inputs": {
                  "method": "GET",
                  "uri": "https://httpstat.us/200"
               },
               "runAfter": {},
               "type": "Http"
            }
         },
         "foreach": "@triggerBody()",
         "runAfter": {},
         "type": "Foreach"
      }
   }
}
```

(note that there is also a Trigger, and a Response action, not shown above).

In Logic Apps Consumption we see this result:
```yaml
[
    {
        "name": "HTTP",
        "outputs": [
            {
                "name": "HTTP",
                "inputs": {
                    "uri": "https://httpstat.us/200",
                    "method": "GET"
                },
                "outputs": {
                    "statusCode": 200,
                    "headers": {
                        "Date": "Fri, 17 Feb 2023 16:29:32 GMT",
                        "Server": "Kestrel",
                        "Set-Cookie": "ARRAffinity=df2a2e6ebbc5e72599f3931ae1225041a3f59161d5bc216d94cb11ea73104275;Path=/;HttpOnly;Secure;Domain=httpstat.us,ARRAffinitySameSite=df2a2e6ebbc5e72599f3931ae1225041a3f59161d5bc216d94cb11ea73104275;Path=/;HttpOnly;SameSite=None;Secure;Domain=httpstat.us",
                        "Request-Context": "appId=cid-v1:xxx",
                        "Strict-Transport-Security": "max-age=2592000",
                        "Content-Length": "6",
                        "Content-Type": "text/plain"
                    },
                    "body": "200 OK"
                },
                "startTime": "2023-02-17T16:29:32.5381006Z",
                "endTime": "2023-02-17T16:29:32.9803813Z",
                "trackingId": "6a06b93d-ca87-49b6-b124-44d16d691092",
                "clientTrackingId": "xxx",
                "code": "OK",
                "status": "Succeeded"
            }
        ],
        "startTime": "2023-02-17T16:29:33.2685883Z",
        "endTime": "2023-02-17T16:29:33.2691767Z",
        "trackingId": "6db91f49-59e4-49dc-85ee-16348f253e9a",
        "clientTrackingId": "xxx",
        "code": "NotSpecified",
        "status": "Succeeded",
        "repetitionCount": 1
    }
]
```

But in Logic Apps Standard (with the same code) we see this:
```yaml
[
    {
        "name": "HTTP",
        "startTime": "2023-02-17T16:24:40.6477084Z",
        "endTime": "2023-02-17T16:24:40.6733837Z",
        "trackingId": "0e0ecf32-a7e4-4159-b15d-680b8bdb3114",
        "clientTrackingId": "xxx",
        "code": "NotSpecified",
        "status": "Succeeded",
        "repetitionCount": 1
    }
]
```

(Note the missing "outputs" property in the Logic Apps Standard result).

(On a separate note, I wondered if this was related to the ability to see the Run History for any items in a For Each when viewing the Run History in the portal? The Logic App Designer appears unable to get the Run History for individual iterations of a For Each).

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a workflow using the sample below
2. Execute the workflow, supplying an array in request
3. Look at response - notice absence of "outputs" field
4. Ideally run same test in Consumption Logic App

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": "@result('For_each')",
                "runAfter": {
                    "For_each": [
                        "Succeeded"
                    ]
                },
                "type": "Compose"
            },
            "For_each": {
                "actions": {
                    "HTTP": {
                        "inputs": {
                            "method": "GET",
                            "retryPolicy": {
                                "type": "none"
                            },
                            "uri": "https://httpstat.us/200"
                        },
                        "runAfter": {},
                        "type": "Http"
                    }
                },
                "foreach": "@triggerBody()",
                "runAfter": {},
                "type": "Foreach"
            },
            "Response": {
                "inputs": {
                    "body": "@outputs('Compose')",
                    "statusCode": 200
                },
                "kind": "http",
                "runAfter": {
                    "Compose": [
                        "Succeeded"
                    ]
                },
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "manual": {
                "inputs": {},
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/11536727/219721810-28b9bba0-1c87-448b-ae99-dfbe889144a6.png)
![image](https://user-images.githubusercontent.com/11536727/219722084-143c461b-d17c-45ee-af03-188cb5f3ac84.png)

AB#17227378
